### PR TITLE
How To Basic : Completely Restructured And Full Localization, Present To You By Gary Bryson Luis Jr.

### PR DESCRIPTION
**Pull request by GBLodb**

### CODE REVIEW

**Review by Dabai1025 — CHANGES_REQUESTED** [review]
1. 在 "20211217\scripts\vanilla\tooltips.zs" 第 49 行，"frients" 应改为 "friends"。
2. 部分变量名无法明了地表达其意义。
3. 优先级数字过大。
4. 请修复 "20211217\scripts\vanilla\recipes.zs" 第 65 行前后存在的问题
```
ERROR: vanilla\recipes.zs65 > Could not get Reference: ingotNameList
ERROR: No iterator with 1 variables
```

1. On line 49 of "20211217\scripts\vanilla\tooltips.zs", "frients" should be "friends".
2. Some variable names cannot express their meaning clearly.
3. The priority number is too large.
4. Please fix the problem around line 65 of "20211217\scripts\vanilla\recipes.zs"
```
ERROR: vanilla\recipes.zs65 > Could not get Reference: ingotNameList
ERROR: No iterator with 1 variables
```

**Comment by XHL315** [comment]
第二项说实话没啥意义，临时变量不应该起这么长的名字

**Comment by GBLodb** [comment]
Item 3 belongs to the personal habit gap, in order to facilitate the interpolation of new special scripts at any time under the premise of the discrete degree of priority numbers designed to be very high. In addition, none of the priorities reach INT_MAX, so please modify them yourself later if you just need to.

The item 1 and 4 will be fixed soon.

**Review by LDS-XiaoYe — APPROVED** [review]

**Review by Dabai1025 — APPROVED** [review]

**Comment by Dabai1025** [comment]
Thanks for your contribution.

**Pull request merged**
